language: python
sudo: false
python:
 - "2.7"
 - "3.4"
 - "3.5"
 - "3.6"
 - "nightly"
 - "pypy"
env:
  matrix:
   - DJANGO="Django>=1.8,<1.9"
   - DJANGO="Django>=1.9,<1.10"
   - DJANGO="Django>=1.10,<1.11"
   - DJANGO="Django>=1.11,<2.0"
   - DJANGO="Django>=2.0,<2.1"
   - DJANGO="https://github.com/django/django/archive/master.tar.gz"
install:
 # The default pip doesn't properly support pre-release version specifiers.
 - pip install -U pip
 - pip install . coverage $DJANGO
branches:
 only:
  - master
  - develop
  - /^feature\/.+/
  - /^release\/.+/
  - /^hotfix\/.+/
  - /^v[\d\.]+/
script: coverage run --source=environ setup.py test
matrix:
  fast_finish: true
  include:
    - python: "3.3"
      env: DJANGO="Django>=1.8,<1.9"
  exclude:
    # Django master dropped support for Python 2.
    - python: "2.7"
      env: DJANGO="Django>=2.0,<2.1"
    - python: "pypy"
      env: DJANGO="Django>=2.0,<2.1"
    - python: "2.7"
      env: DJANGO="https://github.com/django/django/archive/master.tar.gz"
    - python: "pypy"
      env: DJANGO="https://github.com/django/django/archive/master.tar.gz"
  allow_failures:
    - env: DJANGO="https://github.com/django/django/archive/master.tar.gz"
after_success:
  - coverage report
  - pip install --quiet python-coveralls
  - coveralls
