name: Make sure new PRs are sent to develop

on:
  pull_request_target:
    types: [opened, edited]

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: Vankka/pr-target-branch-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target: main
          exclude: develop # Don't prevent going from develop -> main
          change-to: develop
          comment: |
            Your PR was set to target `main`, PRs should be target `develop`
            The base branch of this PR has been automatically changed to `develop`, please check that there are no merge conflicts.
